name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Установка SSH клиента
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      # Шаг 3: Проверка и создание директории, если её нет
      - name: Ensure deployment directory exists
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /var/www/pavvljokesbot

      # Шаг 4: Синхронизация файлов с проверкой .rsync-exclude
      - name: Sync files with rsync
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ -f "/var/www/pavvljokesbot/.rsync-exclude" ]; then
              rsync -av --delete --exclude-from='/var/www/pavvljokesbot/.rsync-exclude' ./ /var/www/pavvljokesbot/
            else
              rsync -av --delete ./ /var/www/pavvljokesbot/
            fi

      # Шаг 5: Создание .env файла с переменными окружения
      - name: Create .env file
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cat <<EOF > /var/www/pavvljokesbot/.env
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            EOF

      # Шаг 6: Установка зависимостей и перезапуск бота
      - name: Install dependencies and restart bot
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/pavvljokesbot
            npm install --production
            pm2 restart index.js || pm2 start index.js --name pavvljokesbot