name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Установка SSH клиента
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      # Шаг 3: Очистка папки на сервере, кроме исключений
      - name: Clean target directory except exclusions
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/pavvljokesbot
            find . -mindepth 1 -not -path "./logs/*" -not -name "logs" -exec rm -rf {} +

      # Шаг 4: Загрузка новых файлов
      - name: Upload project files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./"
          target: "/var/www/pavvljokesbot"

      # Шаг 5: Создание .env файла
      - name: Create .env file
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cat <<EOF > /var/www/pavvljokesbot/.env
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            EOF

      # Шаг 6: Установка зависимостей и перезапуск бота
      - name: Install dependencies and restart bot
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/pavvljokesbot
            npm install --production
            pm2 restart index.js || pm2 start index.js --name pavvljokesbot